---
- name: istalling webserver
  hosts: all
  become: true
  tasks:
    - name: installing nginx
      ansible.builtin.apt:
       name: 
       - httpd
       - nginx
       - unzip
       update_cache: yes
       state: present
    - name: download web site from url
      ansible.builtin.uri:
        url:
        dest: /temp/makan.zip
        remote_src: yes
    - name: unzip zipfile or website zip file
      ansible.builtin.unarchive:
        src: /temp/makan.zip
        dest: /var/www/html
        remote_src: yes
    - name: rename the directory
      ansible.builtin.commend: mv /var/www/html/unzipfile /var/www/html/makkan
    - name: restart nginx
      ansible.builtin.systemd:
        state: restart
        name: nginx
      

       
